trigger:
  # Trigger from semantic version tags (for releasing to prod)
  tags:
    include:
    - '*.*.*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    # Where our templates are sourced from
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      endpoint: github

variables:
  - name: repoName
    value: 'prod-bip/ssb/stratus/bip-initializer'

  - name: imageHost
    value: 'eu.gcr.io'

stages:

# The template makes sure this is only run for "tag" events
- stage: tagForProd
  displayName: Tag Docker Image for production
  jobs:
  - template: docker/docker-tag-for-production.yml@templates
    parameters:
      tagToTag: '$(Build.SourceBranchName)-$(Build.SourceVersion)'
      gcrImageName: '$(imageHost)/$(repoName)'
